[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  functions = "netlify/functions/"
  command = "echo building app"
[[redirects]]
  force = true
  from = "/auth/*"
  status = 200
  to = "/.netlify/functions/index/:splat"